name: Stage Instruction Lint

on:
  pull_request:
    paths:
      - 'stages/**/*.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci

      # Find changed md files in /stages
      - id: changed
        uses: tj-actions/changed-files@v45
        with:
          files: |
            stages/**/*.md

      - name: Lint stage instructions with LLM
        if: steps.changed.outputs.any_changed == 'true'
        run: |
          npx ts-node scripts/llm_stage_lint.ts ${{ steps.changed.outputs.all_changed_files }}
